/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */
// @ts-nocheck

export { default as pluginComments } from '@eslint-community/eslint-plugin-eslint-comments'
export { default as configJs } from '@eslint/js'
export { default as pluginVitest } from '@vitest/eslint-plugin'
export { default as pluginIgnore } from 'eslint-config-flat-gitignore'
export { default as pluginAntfu } from 'eslint-plugin-antfu'
export { default as pluginDeMorgan } from 'eslint-plugin-de-morgan'
export { default as pluginErasableSyntaxOnly } from 'eslint-plugin-erasable-syntax-only'
export { default as pluginImportLite } from 'eslint-plugin-import-lite'
export { default as pluginJsDoc } from 'eslint-plugin-jsdoc'
export { default as pluginJsonc } from 'eslint-plugin-jsonc'
export { default as pluginNode } from 'eslint-plugin-n'
export { default as pluginNoOnlyTests } from 'eslint-plugin-no-only-tests'
export { default as pluginPerfectionist } from 'eslint-plugin-perfectionist'
export { default as pluginUnicorn } from 'eslint-plugin-unicorn'
export { default as pluginUnusedImports } from 'eslint-plugin-unused-imports'
export { default as pluginYaml } from 'eslint-plugin-yml'
export { default as parserJsonc } from 'jsonc-eslint-parser'
export { default as tseslint } from 'typescript-eslint'
export { default as parserYaml } from 'yaml-eslint-parser'
